// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbe8k2bwrweJ2oNQBzH9sFw1nsG5A27I',
    appId: '1:360768034609:android:7d9aa0725ba0f3f24a8210',
    messagingSenderId: '360768034609',
    projectId: 'petcore-5ddcf',
    databaseURL: 'https://petcore-5ddcf-default-rtdb.firebaseio.com',
    storageBucket: 'petcore-5ddcf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6upFKHoRYUolPQgSAPYvpkS4j4d0vH7Q',
    appId: '1:360768034609:ios:9d70d9af036c25cb4a8210',
    messagingSenderId: '360768034609',
    projectId: 'petcore-5ddcf',
    databaseURL: 'https://petcore-5ddcf-default-rtdb.firebaseio.com',
    storageBucket: 'petcore-5ddcf.firebasestorage.app',
    iosBundleId: 'com.example.petcoreApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGVAh4TqVT2ytwb_QOK0niuguqFNED_uU',
    appId: '1:360768034609:web:c2f6bd1552a84ab44a8210',
    messagingSenderId: '360768034609',
    projectId: 'petcore-5ddcf',
    authDomain: 'petcore-5ddcf.firebaseapp.com',
    databaseURL: 'https://petcore-5ddcf-default-rtdb.firebaseio.com',
    storageBucket: 'petcore-5ddcf.firebasestorage.app',
    measurementId: 'G-X6HB40MBM2',
  );
}
